name: Landing Page Development deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "develop" branch
  push:
    branches: ['develop']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.IP_INSTANCE_DEVELOP }}
          BASTION: ${{ secrets.IP_BASTION_DEVELOP }}

        with:
          host: ${{ secrets.IP_INSTANCE_DEVELOP }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          proxy_host: ${{ secrets.IP_BASTION_DEVELOP }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.AWS_PRIVATE_KEY }}
          proxy_port: 22
          script_stop: true
          script: |
            sudo service landing stop 
            cd landing.io/ 
            git checkout develop 
            git pull 
            yarn cache clean 
            yarn install 
            yarn build 
            sudo service landing start 
            exit
            
